"""add_call_and_task_models

Revision ID: 413c83eda220
Revises: 0007_add_appointments_table
Create Date: 2026-07-23 20:36:10.772495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def _create_enum_if_not_exists(name: str, values: list[str]) -> None:
    escaped_values = [value.replace("'", "''") for value in values]
    quoted_values = ", ".join(f"'{value}'" for value in escaped_values)
    exists = op.get_bind().execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = :name"),
        {"name": name},
    ).scalar()
    if exists:
        return
    sql = f"CREATE TYPE {name} AS ENUM ({quoted_values})"
    op.execute(sa.text(sql))


def _enum_type(name: str, values: list[str]):
    return postgresql.ENUM(*values, name=name, create_type=False)

# revision identifiers, used by Alembic.
revision: str = '413c83eda220'
down_revision: Union[str, None] = '0007_add_appointments_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_enum_if_not_exists('call_status', ['received', 'processed', 'escalated'])
    _create_enum_if_not_exists('task_source', ['email', 'call'])
    _create_enum_if_not_exists('task_priority', ['low', 'medium', 'high', 'urgent'])
    _create_enum_if_not_exists('task_status', ['pending', 'in_progress', 'completed', 'escalated'])

    op.create_table('calls',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('status', _enum_type('call_status', ['received', 'processed', 'escalated']), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_case_id'), 'calls', ['case_id'], unique=False)
    op.create_table('tasks',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('source', _enum_type('task_source', ['email', 'call']), nullable=False),
    sa.Column('priority', _enum_type('task_priority', ['low', 'medium', 'high', 'urgent']), nullable=False),
    sa.Column('status', _enum_type('task_status', ['pending', 'in_progress', 'completed', 'escalated']), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_case_id'), 'tasks', ['case_id'], unique=False)
    op.drop_index(op.f('vector_store_embedding_hnsw_idx'), table_name='vector_store', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('vector_store')
    op.drop_index(op.f('chunks_embedding_hnsw_idx'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('chunks_patient_access_idx'), table_name='chunks')
    op.create_index(op.f('ix_chunks_patient_id'), 'chunks', ['patient_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_chunks_patient_id'), table_name='chunks')
    op.create_index(op.f('chunks_patient_access_idx'), 'chunks', ['patient_id', 'access_scope'], unique=False)
    op.create_index(op.f('chunks_embedding_hnsw_idx'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('vector_store',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('document_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], name=op.f('vector_store_case_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('vector_store_pkey'))
    )
    op.create_index(op.f('vector_store_embedding_hnsw_idx'), 'vector_store', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_tasks_case_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_calls_case_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
