"""add_call_and_task_models

Revision ID: 0017_add_call_task_models
Revises: 0016_audit_hash_chain
Create Date: 2026-07-23 20:36:10.772495

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


def _create_enum_if_not_exists(name: str, values: list[str]) -> None:
    escaped_values = [value.replace("'", "''") for value in values]
    quoted_values = ", ".join(f"'{value}'" for value in escaped_values)
    exists = op.get_bind().execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = :name"),
        {"name": name},
    ).scalar()
    if exists:
        return
    sql = f"CREATE TYPE {name} AS ENUM ({quoted_values})"
    op.execute(sa.text(sql))


def _enum_type(name: str, values: list[str]):
    return postgresql.ENUM(*values, name=name, create_type=False)

# revision identifiers, used by Alembic.
revision: str = '0017_add_call_task_models'
down_revision: str | None = "0016_audit_hash_chain"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_enum_if_not_exists('call_status', ['received', 'processed', 'escalated'])
    _create_enum_if_not_exists('task_source', ['email', 'call'])
    _create_enum_if_not_exists('task_priority', ['low', 'medium', 'high', 'urgent'])
    _create_enum_if_not_exists('task_status', ['pending', 'in_progress', 'completed', 'escalated'])

    op.create_table('calls',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column(
        'status', _enum_type('call_status', ['received', 'processed', 'escalated']),
        nullable=False,
    ),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_case_id'), 'calls', ['case_id'], unique=False)
    op.create_table('tasks',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('source', _enum_type('task_source', ['email', 'call']), nullable=False),
    sa.Column(
        'priority', _enum_type('task_priority', ['low', 'medium', 'high', 'urgent']),
        nullable=False,
    ),
    sa.Column(
        'status',
        _enum_type('task_status', ['pending', 'in_progress', 'completed', 'escalated']),
        nullable=False,
    ),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_case_id'), 'tasks', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_case_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_calls_case_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
